# ==== REGRESSION ====
# REFRESH_INTERVAL = 6 * 60 * 60    # 6 hours
REFRESH_INTERVAL = 5 * 60           # 5 minutes
NUM_MEASUREMENTS = 150

# ==== BOUNTIES ====
FALL_POINTS = 100
FIRE_POINTS = 500
CHARGE_POINTS = 25
BATTERY_THRESHOLD = 0.25